apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-hostname
  namespace: default
  labels:
    app: nginx-hostname
spec:
  replicas: 3
  selector:
    app: nginx-hostname
  template:
    metadata:
      labels:
        app: nginx-hostname
    spec:
      containers:
      - name: nginx-hostname
        image: stenote/nginx-hostname
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 30
