apiVersion: v1
kind: Service
metadata:
  name: nginx-hostname
  namespace: default
  labels:
    app: nginx-hostname
spec:
  selector:
    app: nginx-hostname
  externalIPs: [10.0.2.15]
  ports:
  - port: 9091
    targetPort: 80
