#cloud-config
hostname: "coreos-k8s-1"
users:
  - name: "manoon"
    groups:
      - "sudo"
      - "docker"
    passwd: $1$2UKweXyf$/wL8sAqMT8RSZxqYjCtiN.

write_files:
  - path: /etc/systemd/network/10-enp0s8.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      Name=enp0s8
      [Network]
      DNS=8.8.8.8
      Address=172.16.0.1/16
  - path: /etc/kubernetes/kubernetes-master.env
    content: |
      ETCD_ENDPOINTS=http://172.16.0.1:2379
      ADVERTISE_IP=172.16.0.1
      NETWORK_PLUGIN=cni
      POD_NETWORK=10.1.0.0/16
      SERVICE_IP_RANGE=172.17.0.0/16
      K8S_SERVICE_IP=172.17.0.1
      DNS_SERVICE_IP=172.17.0.10
      KUBELET_IMAGE_TAG=v1.5.4_coreos.0
  - path: /etc/flannel/options.env
    content: |
      FLANNELD_IFACE=172.16.0.1
      FLANNELD_ETCD_ENDPOINTS=http://172.16.0.1:2379
      POD_NETWORK=10.1.0.0/16
      POD_SUBNET_LEN=24
  - path: /etc/kubernetes/cni/docker_opts_cni.env
    content: |
      DOCKER_OPT_BIP=""
      DOCKER_OPT_IPMASQ=""
  - path: /etc/kubernetes/manifests/kube-apiserver.yaml
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-apiserver
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-apiserver
          image: quay.io/coreos/hyperkube:v1.5.4_coreos.0
          command:
          - /hyperkube
          - apiserver
          - --insecure-bind-address=0.0.0.0
          - --insecure-port=8080
          - --etcd-servers=${ETCD_ENDPOINTS}
          - --allow-privileged=true
          - --service-cluster-ip-range=${SERVICE_IP_RANGE}
          - --advertise-address=${ADVERTISE_IP}
          - --admission-control=NamespaceLifecycle,LimitRanger,DefaultStorageClass,ResourceQuota
          - --runtime-config=extensions/v1beta1/networkpolicies=true
          - --anonymous-auth=false
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              port: 8080
              path: /healthz
            initialDelaySeconds: 15
            timeoutSeconds: 15
          ports:
          - containerPort: 8080
            hostPort: 8080
            name: http
  - path: /etc/kubernetes/manifests/kube-controller-manager.yaml
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-controller-manager
        namespace: kube-system
      spec:
        hostNetwork: true
        containers:
        - name: kube-controller-manager
          image: quay.io/coreos/hyperkube:v1.5.4_coreos.0
          command:
          - /hyperkube
          - controller-manager
          - --master=http://127.0.0.1:8080
          - --leader-elect=true
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: 10252
            initialDelaySeconds: 15
            timeoutSeconds: 15
locksmith:
  reboot_strategy: "off"
coreos:
  ####
  # etcd2: stand-alone mode
  ####
  etcd2:
    name: etcdserver
    initial-cluster: etcdserver=http://172.16.0.1:2380
    initial-advertise-peer-urls: http://172.16.0.1:2380
    advertise-client-urls: http://172.16.0.1:2379
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://0.0.0.0:2380
  units:
    - name: restart-network.service
      command: start
      content: |
        [Unit]
        Description=Restart network
        Before=flanneld.service kubelet-install-cni.service kubelet-overwrite-manifests.service
        [Service]
        ExecStart=/usr/bin/systemctl restart systemd-networkd
        Type=oneshot
    - name: etcd2.service
      command: start
    - name: flanneld.service
      drop-ins:
      - name: 50-network-config.conf
        content: |
          [Unit]
          Description=Flanneld Service
          After=restart-network.service
          [Service]
          ExecStartPre=/usr/bin/ln -sf /etc/flannel/options.env /run/flannel/options.env
          ExecStartPre=/usr/bin/etcdctl -endpoints ${FLANNELD_ETCD_ENDPOINTS} set /coreos.com/network/config '{ "Network": "${POD_NETWORK}", "SubnetLen": ${POD_SUBNET_LEN}, "Backend":{"Type":"vxlan"} }'
    - name: docker.service
      drop-ins:
      - name: 40-flanneld.conf
        content: |
          [Unit]
          Requires=flanneld.service
          After=flanneld.service
          [Service]
          EnvironmentFile=/etc/kubernetes/cni/docker_opts_cni.env
      command: start

    - name: kubelet-overwrite-manifests.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Overwrite kubernetes manifests. This service read kubernetes-master.env and certificate in /etc/kubernetes/ssl
        After=restart-network.service network-online.target
        Before=kubelet.service
        Wants=network-online.target

        [Service]
        Type=oneshot
        ExecStartPre=/usr/bin/mkdir -p /opt/bin
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/cni/net.d

        ExecStartPre=/usr/bin/wget -q -O /opt/bin/kubelet-wrapper https://raw.githubusercontent.com/napat1412/kubernetes-manifests/v1.5.4/bin/kubelet-wrapper
        ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet-wrapper
        ExecStartPre=/usr/bin/wget -q -O /opt/bin/sed.sh https://raw.githubusercontent.com/napat1412/kubernetes-manifests/v1.5.4/bin/sed.sh
        ExecStartPre=/usr/bin/chmod +x /opt/bin/sed.sh

        ExecStartPre=/usr/bin/wget -q -O /etc/kubernetes/cni/net.d/10-flannel.conf https://raw.githubusercontent.com/napat1412/kubernetes-manifests/v1.5.4/deploy-master/kubernetes/cni/net.d/10-flannel.conf

        ExecStartPre=/usr/bin/wget -q -O /etc/kubernetes/manifests/kube-scheduler.yaml https://raw.githubusercontent.com/napat1412/kubernetes-manifests/v1.5.4/deploy-master/kubernetes/manifests/kube-scheduler.yaml
        ExecStartPre=/usr/bin/wget -q -O /etc/kubernetes/manifests/kube-proxy.yaml https://raw.githubusercontent.com/napat1412/kubernetes-manifests/v1.5.4/deploy-master/kubernetes/manifests/kube-proxy.yaml

        EnvironmentFile=/etc/kubernetes/kubernetes-master.env
        ExecStartPre=/opt/bin/sed.sh ETCD_ENDPOINTS ${ETCD_ENDPOINTS} /etc/kubernetes/manifests/kube-apiserver.yaml
        ExecStartPre=/opt/bin/sed.sh SERVICE_IP_RANGE ${SERVICE_IP_RANGE} /etc/kubernetes/manifests/kube-apiserver.yaml
        ExecStartPre=/opt/bin/sed.sh ADVERTISE_IP ${ADVERTISE_IP} /etc/kubernetes/manifests/kube-apiserver.yaml
        ExecStartPre=/opt/bin/sed.sh KUBELET_IMAGE_TAG ${KUBELET_IMAGE_TAG} /etc/kubernetes/manifests/kube-apiserver.yaml
        ExecStartPre=/opt/bin/sed.sh KUBELET_IMAGE_TAG ${KUBELET_IMAGE_TAG} /etc/kubernetes/manifests/kube-controller-manager.yaml
        ExecStartPre=/opt/bin/sed.sh KUBELET_IMAGE_TAG ${KUBELET_IMAGE_TAG} /etc/kubernetes/manifests/kube-scheduler.yaml
        ExecStart=/opt/bin/sed.sh KUBELET_IMAGE_TAG ${KUBELET_IMAGE_TAG} /etc/kubernetes/manifests/kube-proxy.yaml

    - name: kubelet-install-cni.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Install cni (container networking) & kubectl
        After=restart-network.service network-online.target
        Wants=network-online.target

        [Service]
        Type=oneshot
        ExecStartPre=/usr/bin/mkdir -p /opt/cni/bin
        ExecStartPre=/usr/bin/wget -q -O /opt/cni/cni-v0.4.0.tgz https://github.com/containernetworking/cni/releases/download/v0.4.0/cni-amd64-v0.4.0.tgz
        ExecStartPre=/usr/bin/tar -xvf /opt/cni/cni-v0.4.0.tgz -C /opt/cni/bin
        ExecStartPre=/usr/bin/wget -q -O /opt/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.5.4/bin/linux/amd64/kubectl
        ExecStart=/usr/bin/chmod +x /opt/bin/kubectl

    - name: kubelet.service
      runtime: true
      command: start
      content: |
        [Unit]
        Requires=docker.service
        After=kubelet-overwrite-manifests.service
        
        [Service]
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
        ExecStartPre=/usr/bin/mkdir -p /var/log/containers
        ExecStartPre=/usr/bin/mkdir -p /opt/cni/bin
        EnvironmentFile=/etc/kubernetes/kubernetes-master.env
        Environment="RKT_RUN_ARGS=--uuid-file-save=/var/run/kubelet-pod.uuid \
          --volume dns,kind=host,source=/etc/resolv.conf \
          --mount volume=dns,target=/etc/resolv.conf \
          --volume var-log,kind=host,source=/var/log \
          --mount volume=var-log,target=/var/log \
          --volume cni-bin,kind=host,source=/opt/cni/bin \
          --mount volume=cni-bin,target=/opt/cni/bin"
        ExecStartPre=/usr/bin/docker pull quay.io/coreos/hyperkube:${KUBELET_IMAGE_TAG}
        ExecStartPre=/usr/bin/rkt trust --prefix="quay.io/coreos/hyperkube" --skip-fingerprint-review
        ExecStartPre=/usr/bin/rkt fetch quay.io/coreos/hyperkube:${KUBELET_IMAGE_TAG}
        ExecStartPre=-/usr/bin/rkt rm --uuid-file=/var/run/kubelet-pod.uuid
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --api-servers=http://127.0.0.1:8080 \
          --register-schedulable=false \
          --cni-conf-dir=/etc/kubernetes/cni/net.d \
          --network-plugin=${NETWORK_PLUGIN} \
          --container-runtime=docker \
          --allow-privileged=true \
          --pod-manifest-path=/etc/kubernetes/manifests \
          --hostname-override=${ADVERTISE_IP} \
          --cluster_dns=${DNS_SERVICE_IP} \
          --cluster_domain=cluster.local
        ExecStop=-/usr/bin/rkt stop --uuid-file=/var/run/kubelet-pod.uuid
        Restart=always
        RestartSec=30
        TimeoutSec=180min

        [Install]
        WantedBy=multi-user.target
